# fly.toml app configuration file generated for young-glade-7986 on 2023-06-04T17:49:28+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "young-glade-7986"
primary_region = "cdg"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080 
  processes = ["app"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
